name = "stefanuk12/luau_defs"
version = "0.2.1"
description = "Luau definitions for a Roblox exploit environment, based upon sUNC."
authors = ["Stefanuk12"]
repository = "https://github.com/rocult/luau-defs"
license = "MIT"
includes = [
    "pesde.toml",
    "README.md",
    "LICENSE",
    "types",
    "docs",
]

[target]
environment = "luau"
